### ISSUE TITLE
update from D7 missing

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/auto_nodetitle#16]
It looks like this project still needs an update hook, so people coming from Drupal 7 won't lose their settings.

**Comment by quicksketch** [comment]
I believe this was added in https://github.com/backdrop-contrib/auto_nodetitle/commit/392ca0c566f31e41ffaaa53fc00fba59e301961b. It doesn't look like it was tracked to this issue, but it was fixed Jan 3, 2020 and is in the current release.
