### ISSUE TITLE
Your release tags are not working out

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/auto_nodetitle#2]
Hi @biolithic 
Youre using 'v1.0' as your tag. Its causing you to get errors from the GitHub/Project module hooks. See  https://github.com/backdrop-contrib/auto_nodetitle/releases/download/v1.1/PACKAGING_ERROR_LOG.txt. This means your projects will not be listed on Backdrop.org.

You should use the format 1.x-x.x.x  for your tag/release. (e.g 1.x-1.0.0)

Just in case you were planning a mass release for all your modules; don't want you wasting your day. :smile:

**Comment by biolithic** [comment]
It's a good thing I noticed this email, because I was just about to release
or re-release stuff.
Thanks!

**Comment by jenlampton** [comment]
These seem to be working now, so closing this issue  :)
