### ISSUE TITLE
Missing argument warning.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/auto_nodetitle#20]
I am getting another error report -
Warning: Missing argument 3 for auto_nodetitle_node_type_form_submit(), called in ......httpdocs/backdrop/core/includes/form.inc on line 1542 and defined in auto_nodetitle_node_type_form_submit() (line 190 of ...../httpdocs/backdrop/modules/auto_nodetitle/auto_nodetitle.module).
I think the argument $form_id is redundant?

@biolithic please could we have a new release of this module? I am using it on a site.

**Comment by jenlampton** [comment]
> I think the argument $form_id is redundant?

Yes, that should be removed.
