### ISSUE TITLE
Request to help maintain this module

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/auto_nodetitle#21]
I'm using this module and would like to help maitain it. @biolithic, would I have your permission to do so?

**Comment by biolithic** [comment]
Yes you may, happy Backdropping!

**Comment by robertgarrigos** [comment]
Thanks @biolithic

**Comment by jenlampton** [comment]
@robertgarrigos can you submit a PR for this issue that adds your name to the readme? Then we can merge + close this issue :)

**Comment by robertgarrigos** [comment]
done. Should I merge my self?

**Comment by jenlampton** [comment]
@robertgarrigos yep, you've been given permission :)

**Comment by robertgarrigos** [comment]
good. done
