### ISSUE TITLE
Get latest updates from Drupal 7

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/auto_nodetitle#29]
There seem to be a few new commits available that can probably be merged https://git.drupalcode.org/project/auto_nodetitle/commits/7.x-1.x.

Oddly, they haven't bothered to make a new release since 2011 despite all the new work. Seems like being a bit too much on the safe side.

**Comment by herbdool** [comment]
I've got a PR https://github.com/backdrop-contrib/auto_nodetitle/pull/30

**Comment by robertgarrigos** [comment]
Merged
