### ISSUE TITLE
Remove the ability to use PHP, since there is no PHP module in Backdrop.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/auto_nodetitle#3]
I installed this module, but was unable to use it out-of-the box. Instead there was some cryptic note about commenting out code in the module to use PHP. I didn't want to use PHP (I just wanted to use tokens) but even that was not possible with the current state of the code.

I propose that we remove the ability to use PHP code in node titles completely.  Now that we have tokens in core, this module should do almost everything people need without PHP.  If people want PHP code in their titles they should really be writing their own modules, but there could also be an extension to this module that allows PHP code.

For now, let's remove the PHP so that we can get the token integration working smoothly.

**Comment by klonos** [comment]
...just one issue with that. What about people that migrate from Drupal and have actually set their website with PHP code used in their auto-nodetitles?

At the very least, we should throw a warning or something to let them know before they make the move.

**Comment by klonos** [comment]
Perhaps ...because this module is not a complete port of the Drupal equivalent, we can create a new (say "auto_token_nodetitle") module and have this repo (README.md) point to that project as an alternative explaining the whole situation?

**Comment by jenlampton** [comment]
@klonos the [Upgrade Instructions](https://backdropcms.org/upgrade-from-drupal) are very clear that you need to disable and remove the PHP filter module before moving to Backdrop. Likewise, I don't think we should support any PHP use in Backdrop contrib.  

If someone needs PHP, they should be writing a module to handle it (not putting it in the UI). 

If they absolutely positively need it in the UI, then they can create an add-on module (depends on bad judgement) that adds it as an option. It certainly shouldn't be available to everyone in the primary project, since that would convey the message to new users that it's okay to put PHP in UIs.

**Comment by klonos** [comment]
Fair enough. I was just trying to account for users moving from Drupal that had the equivalent module installed prior to moving to Backdrop with PHP configured. These users might loose data/functionality and then complain (bad conversion UX) or fill up the queue with issues of things not working simply to get a "Oh, yeah, we removed that feature form the Backdrop port of the module (...because we think it's a bug/security risk)". So just saying.
