### ISSUE TITLE
Title truncated at 70 characters, update to 250

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/auto_nodetitle#36]
I have an automatic node title that is comprised of three different fields. When this title gets longer than 70 characters, it's truncated.  Since title's are allowed to be 255 characters, this limit should be updated.

**Comment by yorkshire-pudding** [comment]
I can confirm the issue and that the PR fixes it.
@robertgarrigos - any plans to merge?

**Comment by robertgarrigos** [comment]
Done merge and new release. Thanks!!
