### ISSUE TITLE
Use token link instead of displaying all tokens in the form

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/auto_nodetitle#38]
When configuring any content type, Auto Node Title can drastically slow down the loading of the page because the token browser can easily become very large. Instead of displaying the token browser on the form directly, it should use the `theme('token_tree_link')` link instead, which opens a modal dialog.

![image](https://user-images.githubusercontent.com/100206/186228280-bc9e2751-e414-451e-881b-02c1ec724ce4.png)

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop-contrib/auto_nodetitle/pull/39 that helps with this issue. It could be made more similar to other places in core... normally the token link is appended to the description rather than being a stand-alone element. But either way this one-word change makes a huge improvement in the performance of loading a content type form.

**Comment by yorkshire-pudding** [comment]
@quicksketch - I agree it makes sense to align with the others with a link, but in terms of token browser slowing things down, have you tried [fast_token_browser](https://github.com/backdrop-contrib/fast_token_browser) ?

**Comment by quicksketch** [comment]
@yorkshire-pudding No I haven't! Neat project. In the mean time we actually got around this problem entirely by avoiding using Entity Tokens (which seems to cause this problem frequently). Thanks!
