### ISSUE TITLE
Pattern for the title textfield requires a maximum length to be defined

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/auto_nodetitle#43]
## Description of the bug

The field that allows the user to enter in the _pattern for the title_ , `ant_pattern`, does not have a maximum length specified and therefore the default value given to this field is 128 characters.

The issue occurs when you have a pattern that exceeds 128 characters. The pattern may consist of long token values which will consumer the 128 character limit.

This is more an an annoyance than anything else but could cause a developer to implement a `hook_form_FORM_ID` to modify that field to accept a greater character length.

## Expected Behavior

The field above should accept 255 characters because tokens of longer length will instantly eat up the 128 character limit.

**Comment by olafgrabienski** [comment]
This issue sounds similar to https://github.com/backdrop-contrib/auto_nodetitle/issues/36. Is is somehow related?

**Comment by robertgarrigos** [comment]
This PR (#44) should fix this. Do you want to test it?

**Comment by rbargerhuff** [comment]
> This PR (#44) should fix this. Do you want to test it?

Tested the PR and it worked flawlessly. Thank you for your quick response!!
