### ISSUE TITLE
Error with Inline Entity Form - Undefined array key "#node" in auto_nodetitle_inline_entity_form_entity_form_alter()

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/auto_nodetitle#50]
When using Auto NodeTitle with Inline Entity Form, I get this error when I click on "Add new node."

![image](https://github.com/user-attachments/assets/9ae21c5c-1dde-46e3-a7d0-4928722957c9)

![image](https://github.com/user-attachments/assets/b2be63af-96c1-4444-a627-803b4821a944)

```
Warning: Undefined array key "#node" in auto_nodetitle_inline_entity_form_entity_form_alter() (line 46 of /var/www/html/modules/auto_nodetitle/auto_nodetitle.module).
Warning: Attempt to read property "type" on null in auto_nodetitle_inline_entity_form_entity_form_alter() (line 46 of /var/www/html/modules/auto_nodetitle/auto_nodetitle.module).
```

I'm not sure if the error is with Auto Node Title or Inline Entity Form. 

I will try to do some more testing and update this ticket.

**Comment by argiepiano** [comment]
Try replacing line 46 of `auto_nodetitle.module` for:
```php
    $setting = config_get('auto_nodetitle.settings', 'ant_' . $entity_form['#entity']->type);
```

**Comment by stpaultim** [comment]
@argiepiano - That seems to solve the problem for me!

**Comment by stpaultim** [comment]
@argiepiano Thanks for quick response. Do you want to submit a PR with this change or should I?

**Comment by argiepiano** [comment]
Go ahead!
